yaml
   version: '3'
   services:
     namenode:
       image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
       container_name: namenode
       ports:
         - "9870:9870"
         - "9000:9000"
       environment:
         - CLUSTER_NAME=test
         - CORE_CONF_hadoop_http_staticuser_user=root
         - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
         - HDFS_CONF_dfs_replication=1
       volumes:
         - namenode:/hadoop/dfs/name
       networks:
         - hadoop
     
     datanode:
       image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
       container_name: datanode
       ports:
         - "9864:9864"
       environment:
         - CORE_CONF_hadoop_http_staticuser_user=root
         - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
         - HDFS_CONF_dfs_replication=1
       volumes:
         - datanode:/hadoop/dfs/data
       networks:
         - hadoop

   volumes:
     namenode:
     datanode:

   networks:
     hadoop:
